import { supabaseAdmin as supa } from "@/lib/supabaseAdmin"
import { NextResponse } from "next/server"
import { notifyClubMembers } from "@/lib/notifyAudience"
import { notifyEventAttendees } from "@/lib/notifyEventAttendees"
import { needsSpaceValidation, fetchLocation } from "@/lib/eventClash"
import { findAnyRoomConflict } from "@/lib/spaceBookings"
import { notifyRequestOnlySpace } from "@/lib/notifyRequestOnlySpace"
import { validateBringRequirement } from "@/lib/attendees"

// Club event create/edit — moved server-side (2026-07-23) as part of the Event
// Clash / Space Booking scope (Social_Hive_Event_Clash_Space_Booking_Scope.md,
// §3, locked decision). Previously ClubHome.js inserted/updated `events`
// directly from the browser via the Supabase client, with no server route in
// between -- fine for an ordinary write, but a same-space overlap check has to
// be authoritative, and a client can't be trusted to self-report "I checked,
// there's no clash." Social (/api/social) and Movies (/api/screenings) already
// worked this way; this brings Clubs in line.
//
// Book upsert stays client-side (ClubHome.js) -- the `books` table isn't
// security-relevant and that flow is unchanged. Only the `events` row itself,
// coordinators, notifications, and (on edit) recurring-series scope
// propagation move through this route.
//
// Known gap, scoped out deliberately: recurring SERIES occurrences (Cards,
// Dinner Club -- event_series.mode:'series') generated by /api/series /
// lib/generateSeriesEvents.js / the daily top-up cron do NOT yet run this
// space-clash check. That pipeline is a separate, already-shipped feature;
// touching its generation logic wasn't in scope for this pass. Solo events,
// Book Club's mode:'pattern' events, Social, and Movies are all covered.
export const dynamic = "force-dynamic"

// Same eligibility model as /api/series: admin, this club's owner, or EC of
// any of this club's events.
async function resolve(req, clubId) {
  const token = req.headers.get("Authorization")?.replace("Bearer ", "")
  if (!token) return { error: "Unauthorised", status: 401 }
  const { data: { user } } = await supa.auth.getUser(token)
  if (!user) return { error: "Unauthorised", status: 401 }
  const { data: member } = await supa.from("members").select("id, is_admin").eq("auth_id", user.id).single()
  if (!member) return { error: "Member not found", status: 403 }
  if (member.is_admin) return { member }
  const { data: owner } = await supa.from("space_owners")
    .select("id").eq("context_type", "club").eq("context_key", clubId).eq("member_id", member.id).maybeSingle()
  if (owner) return { member }
  const { data: ec } = await supa.from("event_coordinators")
    .select("id, events!inner(club_id)").eq("member_id", member.id).eq("events.club_id", clubId).limit(1)
  if (ec?.length) return { member }
  return { error: "Not allowed for this group/club", status: 403 }
}

// ID is the truth, name derived from it — see the note in app/api/social/route.js.
async function validateSpace(payload, excludeEventId) {
  if (payload.location_type !== "onsite") return { location_id: null }

  const loc = await fetchLocation(supa, payload.location_id)
  if (!loc) return { error: "Choose a venue for this on-site event", status: 400 }

  if (!needsSpaceValidation({ location_type: payload.location_type, bookable: loc.bookable }))
    return { location_id: loc.id, location: loc.name, request_only: !!loc.request_only }

  if (!payload.event_end_time) return { error: "An end time is required for events in a common space", status: 400 }
  const conflict = await findAnyRoomConflict(supa, {
    location_id: loc.id, event_date: payload.event_date, event_time: payload.event_time,
    event_end_time: payload.event_end_time, exclude_event_id: excludeEventId, locationName: loc.name,
  })
  if (conflict) return { error: conflict.message, status: 409 }
  return { location_id: loc.id, location: loc.name, request_only: !!loc.request_only }
}

const FIELDS = ["club_id", "event_date", "event_time", "event_end_time", "title", "is_public", "show_attendee_names",
  "description", "welcome_message", "book_id", "kit_return_date", "book_return_date", "reservation_cutoff", "max_seats",
  "location_type", "location", "location_id", "max_seats_per_booking", "allow_nonresident_guests", "require_attendee_names", "payment_required", "cost",
  "payment_due_by", "bring_category_ids", "bring_required", "theme_name", "book_snapshot"]

function buildPayload(body, isInsert) {
  const payload = {}
  for (const k of FIELDS) if (k in body) payload[k] = body[k]
  if (isInsert) { payload.hub_type = "club"; payload.archived = false }
  return payload
}

export async function POST(req) {
  const body = await req.json().catch(() => ({}))
  if (!body.club_id) return NextResponse.json({ error: "club_id required" }, { status: 400 })
  const { error, status, member } = await resolve(req, body.club_id)
  if (error) return NextResponse.json({ error }, { status })

  const payload = buildPayload(body, true)
  const bringCheck = validateBringRequirement(payload)
  if (!bringCheck.ok) return NextResponse.json({ error: bringCheck.error }, { status: 400 })
  const space = await validateSpace(payload)
  if (space.error) return NextResponse.json({ error: space.error }, { status: space.status })
  payload.location_id = space.location_id
  if (space.location) payload.location = space.location

  const { data: event, error: insErr } = await supa.from("events").insert(payload).select("id").single()
  if (insErr) return NextResponse.json({ error: insErr.message }, { status: 500 })

  if (Array.isArray(body.coordinator_ids) && body.coordinator_ids.length) {
    await supa.from("event_coordinators").insert(body.coordinator_ids.map(id => ({ event_id: event.id, member_id: id })))
  }

  // "Request Only" (Iain, 2026-08-04): Admin/EC/club owner is trusted to
  // have already talked to Ingenia, but gets a reminder to validate it.
  if (space.request_only) {
    await notifyRequestOnlySpace({
      actingMemberId: member.id, eventId: event.id, eventTitle: payload.title || "event",
      eventDate: payload.event_date, locationName: space.location,
    })
  }

  const { data: club } = await supa.from("clubs").select("name").eq("id", body.club_id).single()
  const when = payload.event_date ? new Date(payload.event_date + "T00:00:00").toLocaleDateString("en-AU", { weekday: "short", day: "numeric", month: "short" }) : ""
  await notifyClubMembers(supa, body.club_id, event.id, "event_added",
    `New ${club?.name || "club"} event: ${payload.title || "event"}${when ? ` — ${when}` : ""}`, { excludeMemberId: member.id })

  return NextResponse.json({ ok: true, id: event.id })
}

export async function PATCH(req) {
  const body = await req.json().catch(() => ({}))
  const { event_id, series_scope } = body
  if (!event_id) return NextResponse.json({ error: "event_id required" }, { status: 400 })

  const { data: existing } = await supa.from("events")
    .select("id, club_id, series_id, event_date, event_time, location, location_id, title, bring_required, bring_category_ids").eq("id", event_id).single()
  if (!existing) return NextResponse.json({ error: "Event not found" }, { status: 404 })

  const { error, status, member } = await resolve(req, existing.club_id)
  if (error) return NextResponse.json({ error }, { status })

  const payload = buildPayload(body, false)
  const bringCheck = validateBringRequirement({
    bring_required: "bring_required" in payload ? payload.bring_required : existing.bring_required,
    bring_category_ids: "bring_category_ids" in payload ? payload.bring_category_ids : existing.bring_category_ids,
  })
  if (!bringCheck.ok) return NextResponse.json({ error: bringCheck.error }, { status: 400 })
  const space = await validateSpace({ ...existing, ...payload }, event_id)
  if (space.error) return NextResponse.json({ error: space.error }, { status: space.status })
  payload.location_id = space.location_id
  if (space.location) payload.location = space.location

  const { error: updErr } = await supa.from("events").update(payload).eq("id", event_id)
  if (updErr) return NextResponse.json({ error: updErr.message }, { status: 500 })

  // "Request Only" (Iain, 2026-08-04): only nudge when the room actually
  // changed onto a Request Only venue -- not on every unrelated edit.
  if (space.request_only && existing.location_id !== payload.location_id) {
    await notifyRequestOnlySpace({
      actingMemberId: member.id, eventId: event_id, eventTitle: payload.title || existing.title || "event",
      eventDate: payload.event_date || existing.event_date, locationName: space.location,
    })
  }

  if (Array.isArray(body.coordinator_ids)) {
    await supa.from("event_coordinators").update({ replaced_at: new Date().toISOString() }).eq("event_id", event_id).is("replaced_at", null)
    if (body.coordinator_ids.length) await supa.from("event_coordinators").insert(body.coordinator_ids.map(id => ({ event_id, member_id: id })))
  }

  // Recurring-series edit scope -- unchanged semantics from ClubHome's old
  // client-side logic, delegated to /api/series which already owns it.
  if (existing.series_id) {
    const authHeader = req.headers.get("Authorization")
    if (series_scope === "future") {
      const PROP = ["title", "description", "welcome_message", "event_time", "event_end_time", "location_type",
        "location", "location_id", "max_seats", "max_seats_per_booking", "allow_nonresident_guests", "require_attendee_names",
        "payment_required", "cost", "bring_category_ids", "bring_required", "theme_name", "is_public", "show_attendee_names"]
      const fields = {}
      for (const k of PROP) if (k in payload) fields[k] = payload[k]
      await fetch(new URL("/api/series", req.url), {
        method: "PATCH", headers: { "Content-Type": "application/json", Authorization: authHeader },
        body: JSON.stringify({ action: "update_future", series_id: existing.series_id, event_id, from_date: payload.event_date || existing.event_date, ...fields }),
      }).catch(() => {})
      if (body.recur && body.recur_changed) {
        await fetch(new URL("/api/series", req.url), {
          method: "PATCH", headers: { "Content-Type": "application/json", Authorization: authHeader },
          body: JSON.stringify({ action: "change_recurrence", series_id: existing.series_id, ...body.recur }),
        }).catch(() => {})
      }
    } else {
      await supa.from("events").update({ is_series_exception: true }).eq("id", event_id)
    }
  }

  const detailsChanged = (payload.event_date && payload.event_date !== existing.event_date)
    || ("event_time" in payload && payload.event_time !== existing.event_time)
    || ("location" in payload && payload.location !== existing.location)
  if (detailsChanged) {
    await notifyEventAttendees(supa, event_id, "event_updated",
      `${payload.title || existing.title || "An event you booked"} has been updated — check the new date, time or location.`,
      { excludeMemberId: member.id })
  }

  return NextResponse.json({ ok: true })
}
