#!/usr/bin/env python3
"""
DVD Library Import Script
=========================
Converts the DVD_Library_Master Google Sheet (exported as CSV) into a
Supabase SQL migration that inserts all titles into the `movies` table
with `we_own = true`.

USAGE
-----
1. Export DVD_Library_Master sheet as CSV:
   File -> Download -> Comma Separated Values (.csv)
   Save as: scripts/dvd_library_input.csv

2. Run:
   python3 scripts/import_dvd_library.py

3. Output: scripts/dvd_library_output.sql
   Copy-paste into Supabase SQL Editor and run.

EXPECTED CSV COLUMNS (in order)
---------------------------------
Index, Title, Category, Year, Genre, Rating, Notes, IMDB_ID

  Index    - F001 / TV001 / MC001 / SD001 etc.
  Title    - Display title
  Category - Film | TV Series | Music & Concert | Sports & Documentary
  Year     - 4-digit year for films; season label for TV (e.g. Season 1)
  Genre    - e.g. Comedy / Romance
  Rating   - e.g. 7.6/10 or blank
  Notes    - Free text (copies in library, actors, etc.)
  IMDB_ID  - e.g. tt0108778 or blank

BEHAVIOUR
---------
- Films:   title as-is, year stored, genre as-is
- TV:      title -> "Friends (Season 1)", genre -> "TV Series, Comedy", year NULL
- Music:   genre -> "Music, Rock"
- Docs:    genre kept as-is

Re-running is safe: ON CONFLICT (title) DO NOTHING skips existing rows.
"""

import csv
import re
import sys
from pathlib import Path

INPUT_FILE  = Path(__file__).parent / "dvd_library_input.csv"
OUTPUT_FILE = Path(__file__).parent / "dvd_library_output.sql"


def esc(s):
    return s.replace("'", "''") if s else s


def parse_rating(raw):
    if not raw or not raw.strip():
        return None
    m = re.match(r"([\d.]+)", raw.strip())
    return m.group(1) if m else None


def is_year(s):
    return bool(re.match(r"^\d{4}$", s.strip())) if s else False


def build_title(title, category, year_or_season):
    if category == "Film" or not year_or_season.strip():
        return title
    return "{} ({})".format(title, year_or_season.strip())


def build_genre(genre, category):
    g = genre.strip()
    if category == "TV Series":
        return "TV Series, {}".format(g) if g else "TV Series"
    if category == "Music & Concert":
        return "Music, {}".format(g) if g else "Music & Concert"
    if category == "Sports & Documentary":
        return g if g else "Documentary"
    return g if g else None


def sql_str(val):
    if val is None or val == "":
        return "NULL"
    return "'{}'".format(esc(val))


def generate(rows):
    header = (
        "-- DVD Library import -- generated by scripts/import_dvd_library.py\n"
        "-- Safe to re-run: ON CONFLICT (title) DO NOTHING skips existing rows.\n\n"
        "INSERT INTO movies (title, year, genre, rating_imdb, imdb_id, we_own, plot)\nVALUES\n"
    )

    values = []
    for row in rows:
        category       = row.get("Category", "Film").strip()
        title_raw      = row.get("Title", "").strip()
        year_or_season = row.get("Year", "").strip()
        genre_raw      = row.get("Genre", "").strip()
        rating_raw     = row.get("Rating", "").strip()
        notes          = row.get("Notes", "").strip()
        imdb_id        = row.get("IMDB_ID", "").strip()

        if not title_raw:
            continue

        display_title = build_title(title_raw, category, year_or_season)
        year   = year_or_season if is_year(year_or_season) else None
        genre  = build_genre(genre_raw, category)
        rating = parse_rating(rating_raw)
        imdb   = imdb_id if imdb_id else None
        plot   = notes if notes else None

        values.append(
            "  ({}, {}, {}, {}, {}, true, {})".format(
                sql_str(display_title), sql_str(year), sql_str(genre),
                sql_str(rating), sql_str(imdb), sql_str(plot)
            )
        )

    footer = "\nON CONFLICT (title) DO NOTHING;\n"
    return header + ",\n".join(values) + footer


def main():
    if not INPUT_FILE.exists():
        print("ERROR: Input file not found: {}".format(INPUT_FILE))
        print("Export the DVD_Library_Master sheet as CSV and save it there.")
        sys.exit(1)

    with open(INPUT_FILE, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        print("ERROR: CSV file is empty.")
        sys.exit(1)

    sql = generate(rows)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)

    films = sum(1 for r in rows if r.get("Category", "").strip() == "Film")
    tv    = sum(1 for r in rows if r.get("Category", "").strip() == "TV Series")
    other = len(rows) - films - tv

    print("Done -- {} rows ({} films, {} TV series, {} other)".format(len(rows), films, tv, other))
    print("Output: {}".format(OUTPUT_FILE))
    print("Next: copy-paste dvd_library_output.sql into Supabase SQL Editor and run.")


if __name__ == "__main__":
    main()
