-- Migration 004: DVD Library import
-- Run in Supabase SQL Editor

INSERT INTO movies (title, year, genre, rating_imdb, imdb_id, we_own, plot) VALUES
  ('10 Things I Hate About You', '1999', 'Comedy / Romance', '7.6', NULL, true, NULL),
  ('2 Fast 2 Furious', '2003', 'Action / Crime', '6.5', NULL, true, 'Fast & Furious #2'),
  ('2012', '2009', 'Action / Adventure', '5.9', NULL, true, NULL),
  ('Aladdin', '1992', 'Animation / Family', '7.7', NULL, true, 'Disney animated'),
  ('Alice in Wonderland', '2010', 'Family / Fantasy', '6.6', NULL, true, 'Disney'),
  ('Alien Collection', NULL, NULL, NULL, NULL, true, 'Contents TBC — physical check needed'),
  ('Alien Hunter', '2016', 'Science Fiction / Drama', NULL, NULL, true, 'James Spader'),
  ('Alien: Covenant', '2017', 'Horror / Science Fiction', '6.2', NULL, true, NULL),
  ('All Quiet on the Western Front', '2022', 'War / Drama', '7.7', NULL, true, NULL),
  ('American Pie — Collector''s Edition', '1999', 'Comedy / Romance', '6.6', NULL, true, NULL),
  ('Amélie', '2001', 'Comedy / Romance', '7.9', NULL, true, NULL),
  ('Anchorman', '2004', 'Comedy', '6.7', NULL, true, NULL),
  ('Arabian Nights', '1974', 'Adventure / Fantasy', '6.5', NULL, true, NULL),
  ('Argo', '2012', 'Drama / Thriller', '7.3', NULL, true, NULL),
  ('As It Is in Heaven', '2014', 'Drama', NULL, NULL, true, NULL),
  ('The Astronaut''s Wife', '1999', 'Drama / Science Fiction', '5.6', NULL, true, NULL),
  ('Austin Powers in Goldmember', '2002', 'Comedy / Crime', '6.0', NULL, true, NULL),
  ('Australia', '2008', 'Adventure / Romance', '6.6', NULL, true, 'Nicole Kidman / Hugh Jackman'),
  ('Avatar', '2009', 'Science Fiction / Action', '7.6', NULL, true, NULL),
  ('Back to the Future — Trilogy Boxset', '1985', 'Adventure / Comedy', '8.3', NULL, true, 'Films 1–3 | 3 copies in library'),
  ('Bad Company', '2002', 'Action / Adventure', '5.5', NULL, true, NULL),
  ('Batman Begins', '2005', 'Drama / Crime', '7.7', NULL, true, NULL),
  ('Battle: Los Angeles', '2011', 'Science Fiction / Action', '5.8', NULL, true, NULL),
  ('Battleship', '2012', 'Thriller / Action', '5.9', NULL, true, NULL),
  ('Begin Again', '2014', 'Comedy / Music', '7.2', NULL, true, NULL),
  ('Behind Enemy Lines', '2001', 'Action / Drama', '6.4', NULL, true, NULL),
  ('The Best Exotic Marigold Hotel', '2012', 'Drama / Comedy', '7.0', NULL, true, '2 copies in library'),
  ('Beverly Hills Cop — Special Collector''s Edition', '1984', 'Comedy / Crime', '7.2', NULL, true, NULL),
  ('Bicentennial Man', '1999', 'Drama / Romance', '7.3', NULL, true, NULL),
  ('Big Daddy', '1999', 'Comedy / Drama', '6.5', NULL, true, NULL),
  ('Big Trouble in Little China', '1986', 'Action / Adventure', '7.2', NULL, true, NULL),
  ('The Blue Bird', '1976', 'Adventure / Family', '5.5', NULL, true, NULL),
  ('Blues Brothers / Blues Brothers 2000', NULL, NULL, NULL, NULL, true, 'Double pack'),
  ('Braveheart', '1995', 'Action / Drama', '7.9', NULL, true, NULL),
  ('Bride Wars', '2009', 'Comedy / Romance', '6.3', NULL, true, NULL),
  ('Bright Eyes', '1982', NULL, NULL, NULL, true, 'Shirley Temple'),
  ('Broken Arrow', '1996', 'Action / Thriller', '6.1', NULL, true, NULL),
  ('Brothers Grimm', '2005', 'Adventure / Fantasy', '5.9', NULL, true, NULL),
  ('The Bucket List', '2007', 'Drama / Comedy', '7.2', NULL, true, NULL),
  ('The ''Burbs', '1989', 'Comedy / Horror', '6.8', NULL, true, NULL),
  ('Captain January', '1936', 'Comedy / Family', '6.8', NULL, true, 'Shirley Temple'),
  ('Casualties of War — Extended Edition', '1989', 'Drama / History', '7.2', NULL, true, NULL),
  ('Catherine the Great', '1996', 'Drama / TV Movie', '5.6', NULL, true, NULL),
  ('Cats & Dogs', '2001', 'Family / Comedy', '5.4', NULL, true, NULL),
  ('City Slickers', '1991', 'Comedy / Western', '6.5', NULL, true, NULL),
  ('Classic Comedy Movie Pack', NULL, NULL, NULL, NULL, true, 'Multi-film pack — contents unknown'),
  ('The Color Purple', '1985', 'Drama / History', '7.7', NULL, true, NULL),
  ('Con Air — Extended Edition', '1997', 'Action / Thriller', '6.8', NULL, true, NULL),
  ('Crazy, Stupid, Love.', '2011', 'Comedy / Drama', '7.3', NULL, true, NULL),
  ('Curly Top', '1935', 'Family / Music', '6.5', NULL, true, 'Shirley Temple'),
  ('The Da Vinci Code — Extended Edition', '2006', 'Thriller / Mystery', '6.7', NULL, true, NULL),
  ('Dances with Wolves — Widescreen', '1990', 'Adventure / Drama', '7.8', NULL, true, NULL),
  ('Dante''s Peak — Special Edition', '1997', 'Action / Adventure', '6.2', NULL, true, NULL),
  ('The Dark Knight', '2008', 'Action / Crime', '8.5', NULL, true, NULL),
  ('The Dark Knight Rises', '2012', 'Action / Crime', '7.8', NULL, true, NULL),
  ('Date Night / What Happens in Vegas / Similar', NULL, NULL, NULL, NULL, true, '5-film pack'),
  ('Days of Thunder', '1990', 'Adventure / Action', '6.4', NULL, true, NULL),
  ('Dead Snow', '2009', 'Horror / Comedy', '6.0', NULL, true, 'Norwegian horror'),
  ('Death Becomes Her', '1992', 'Comedy / Fantasy', '6.8', NULL, true, NULL),
  ('Death Race', '2008', 'Action / Thriller', '6.3', NULL, true, NULL),
  ('Death Race 2', '2010', 'Action / Thriller', '5.9', NULL, true, NULL),
  ('Death Race 3: Inferno', '2013', 'Action / Science Fiction', '5.9', NULL, true, NULL),
  ('Desk Set', '1957', 'Comedy / Romance', '7.0', NULL, true, 'Spencer Tracy'),
  ('Desperate Measures', '1998', 'Action / Drama', '6.0', NULL, true, NULL),
  ('Deuce Bigalow: Male Gigolo', '1999', 'Comedy / Romance', '6.0', NULL, true, NULL),
  ('The Devil Wears Prada', '2006', 'Drama / Comedy', '7.4', NULL, true, NULL),
  ('Devil''s Advocate', '1997', 'Horror / Drama', '7.5', NULL, true, '2 copies in library'),
  ('Devil''s Island', '1939', 'Drama', NULL, NULL, true, NULL),
  ('The Devil''s Rejects', '2005', 'Drama / Horror', '6.7', NULL, true, NULL),
  ('Dimples', '1936', 'Drama / Family', NULL, NULL, true, 'Shirley Temple'),
  ('The Divergent Series — Boxset', '2015', 'Action / Science Fiction', '6.4', NULL, true, NULL),
  ('Doctor Zhivago', '1965', 'Drama / Romance', '7.6', NULL, true, NULL),
  ('A Dog''s Purpose', '2017', 'Adventure / Fantasy', '7.6', NULL, true, NULL),
  ('Doomsday', '2008', 'Science Fiction / Action', NULL, NULL, true, NULL),
  ('The Dressmaker', '2015', 'Drama / Comedy', '7.0', NULL, true, NULL),
  ('Drop Dead Fred', '1991', 'Comedy / Fantasy', '5.8', NULL, true, NULL),
  ('Eagle Eye / Disturbia', NULL, NULL, NULL, NULL, true, 'Double feature pack'),
  ('Eat Pray Love', '2010', 'Drama / Romance', '6.2', NULL, true, NULL),
  ('Elizabeth', '1998', 'Drama / History', '7.2', NULL, true, NULL),
  ('End of Days', '1999', 'Action / Horror', '6.1', NULL, true, NULL),
  ('Enemy at the Gates', '2001', 'War / History', '7.4', NULL, true, NULL),
  ('Escape from L.A.', '1996', 'Action / Thriller', '5.9', NULL, true, NULL),
  ('Escape from New York', '1981', 'Action / Thriller', '7.0', NULL, true, NULL),
  ('A Farewell to Arms', '1957', 'Drama / Romance', '6.0', NULL, true, NULL),
  ('Fast & Furious 6', '2013', 'Action / Thriller', '6.8', NULL, true, NULL),
  ('The Fast and the Furious', '2001', 'Action / Crime', '7.0', NULL, true, NULL),
  ('The Fast and the Furious: Tokyo Drift', '2006', 'Action / Crime', '6.5', NULL, true, NULL),
  ('Flags of Our Fathers', '2006', 'War / Drama', '6.9', NULL, true, NULL),
  ('Footloose', '1984', 'Drama / Romance', '6.7', NULL, true, NULL),
  ('For a Few Dollars More', '1965', 'Western', '8.0', NULL, true, NULL),
  ('Forrest Gump — Special Collector''s Edition', '1994', 'Comedy / Drama', '8.5', NULL, true, NULL),
  ('Fracture', '2007', 'Thriller', '7.3', NULL, true, NULL),
  ('Frantic', '1988', 'Mystery / Crime', '6.7', NULL, true, NULL),
  ('The Fugitive — Special Edition', '1993', 'Action / Thriller', '7.5', NULL, true, NULL),
  ('Fury', '2014', 'War / Drama', '7.5', NULL, true, NULL),
  ('Ghost', '1990', 'Fantasy / Romance', '7.2', NULL, true, NULL),
  ('The Ghost and Mrs. Muir', '1947', 'Romance / Fantasy', '7.5', NULL, true, NULL),
  ('Gladiator — Deluxe Collector''s Edition', '2000', 'Action / Drama', '8.2', NULL, true, '2 copies in library'),
  ('Gomorrah', '2008', 'Drama / Crime', '6.9', NULL, true, NULL),
  ('Gone in 60 Seconds', '1974', 'Action / Crime', '6.2', NULL, true, NULL),
  ('Gone in 60 Seconds — Director''s Cut', '1974', 'Action / Crime', '6.2', NULL, true, NULL),
  ('A Good Woman', '2004', 'Comedy / Romance', '6.3', NULL, true, NULL),
  ('Grease — 2 Disc Rockin'' Edition', '1978', 'Romance / Comedy', '7.4', NULL, true, NULL),
  ('The Great Escape', '1963', 'Adventure / Drama', '7.9', NULL, true, NULL),
  ('The Green Mile', '1999', 'Fantasy / Drama', '8.5', NULL, true, NULL),
  ('Gulliver''s Travels', '2010', 'Family / Comedy', '5.2', NULL, true, NULL),
  ('Hancock', '2008', 'Fantasy / Action', '6.4', NULL, true, NULL),
  ('The Happening', '2008', 'Thriller / Science Fiction', '5.4', NULL, true, NULL),
  ('Harry Potter and the Deathly Hallows — Part 2', '2011', 'Adventure / Fantasy', '8.1', NULL, true, NULL),
  ('Harry Potter and the Prisoner of Azkaban', '2004', 'Adventure / Fantasy', '8.0', NULL, true, NULL),
  ('Hart''s War', '2002', 'Drama / War', '6.4', NULL, true, NULL),
  ('The Haunting', '1999', 'Horror / Thriller', '5.5', NULL, true, NULL),
  ('Heat', '1995', 'Crime / Drama', '7.9', NULL, true, NULL),
  ('Heidi', '2015', 'Adventure / Family', '7.3', NULL, true, NULL),
  ('Hello Again', '1987', 'Fantasy / Comedy', '5.7', NULL, true, NULL),
  ('Hocus Pocus', '1993', 'Fantasy / Comedy', '7.0', NULL, true, NULL),
  ('Horny House of Horror', NULL, NULL, NULL, NULL, true, 'R18+'),
  ('Hot Rod', '2007', 'Comedy / Action', '6.4', NULL, true, NULL),
  ('How to Lose a Guy in 10 Days', '2003', 'Comedy / Romance', '6.9', NULL, true, NULL),
  ('The Hunt for Red October', '1990', 'Action / Thriller', '7.4', NULL, true, NULL),
  ('I Give It a Year', '2013', 'Comedy / Romance', '5.5', NULL, true, NULL),
  ('I, Robot', '2004', 'Action / Science Fiction', '7.0', NULL, true, '2 copies in library'),
  ('Inglourious Basterds', '2009', 'Drama / Thriller', '8.2', NULL, true, NULL),
  ('The Internship', '2013', 'Comedy', '6.3', NULL, true, NULL),
  ('Iron Man', '2008', 'Action / Science Fiction', '7.7', NULL, true, NULL),
  ('Iron Man 2', '2010', 'Adventure / Action', '6.9', NULL, true, NULL),
  ('Iron Man 3', '2013', 'Action / Adventure', '6.9', NULL, true, NULL),
  ('Ironclad', '2011', 'Romance / Adventure', '6.2', NULL, true, NULL),
  ('Ironclad 2: Battle for Blood', '2014', 'Action / Adventure', '4.8', NULL, true, NULL),
  ('It''s Complicated', '2009', 'Comedy / Romance', '6.5', NULL, true, NULL),
  ('The Jane Austen Book Club', '2007', 'Comedy / Romance', '6.5', NULL, true, NULL),
  ('Jarhead — Limited Edition', '2005', 'Drama / War', '6.7', NULL, true, NULL),
  ('Jason and the Argonauts', '1963', 'Adventure / Family', '7.2', NULL, true, NULL),
  ('Jerry Bruckheimer Collection', NULL, 'Action / Thriller', NULL, NULL, true, '8-disc collection'),
  ('Jerry Maguire', '1996', 'Comedy / Drama', '7.0', NULL, true, NULL),
  ('Johnny English', '2003', 'Adventure / Action', '6.3', NULL, true, NULL),
  ('Journey to the Centre of the Earth', '2004', 'Adventure / Science Fiction', NULL, NULL, true, NULL),
  ('Jumanji — Collector''s Edition', '1995', 'Adventure / Fantasy', '7.2', NULL, true, NULL),
  ('Just Around the Corner', '1933', 'Comedy / Family', NULL, NULL, true, 'Shirley Temple'),
  ('The King and I', '1956', 'Romance / History', '7.1', NULL, true, NULL),
  ('The King''s Speech', '2010', 'Drama / History', '7.7', NULL, true, '2 copies in library'),
  ('A Knight''s Tale — Collector''s Edition', '2001', 'Adventure / Drama', '6.9', NULL, true, NULL),
  ('Last Man Standing', '1996', 'Crime / Western', '6.4', NULL, true, NULL),
  ('Law Abiding Citizen', '2009', 'Drama / Crime', '7.4', NULL, true, NULL),
  ('Layer Cake', '2004', 'Drama / Thriller', '6.9', NULL, true, NULL),
  ('Le Mans', '1971', 'Action / Drama', '6.8', NULL, true, NULL),
  ('The League of Extraordinary Gentlemen', '2003', 'Fantasy / Action', '6.0', NULL, true, NULL),
  ('Legend', '1985', 'Adventure / Fantasy', '6.2', NULL, true, NULL),
  ('Lethal Weapon Legacy Boxset', '1987', 'Action / Thriller', '7.3', NULL, true, NULL),
  ('Letters from Iwo Jima', '2006', 'Action / Drama', '7.5', NULL, true, NULL),
  ('Life', '1999', 'Comedy / Crime', '6.7', NULL, true, NULL),
  ('Life Is Beautiful', '1997', 'Comedy / Drama', '8.4', NULL, true, NULL),
  ('Life of Pi 3D', '2012', 'Adventure / Drama', '7.4', NULL, true, NULL),
  ('Limitless', '2011', 'Thriller / Mystery', '7.2', NULL, true, NULL),
  ('The Little Colonel', '1935', 'Family / Music', '6.6', NULL, true, 'Shirley Temple'),
  ('Little Fockers', '2010', 'Comedy / Romance', '5.7', NULL, true, NULL),
  ('Little Miss Broadway', '1938', 'Drama / Family', NULL, NULL, true, 'Shirley Temple'),
  ('Little Miss Sunshine', '2006', 'Comedy / Drama', '7.7', NULL, true, NULL),
  ('The Little Rascals', '1994', 'Romance / Comedy', '6.8', NULL, true, NULL),
  ('Lord of the Rings: The Fellowship of the Ring', '2001', 'Adventure / Fantasy', '8.4', NULL, true, '3 copies in library'),
  ('Lord of the Rings: The Return of the King', '2003', 'Adventure / Fantasy', '8.5', NULL, true, '3 copies in library'),
  ('Lord of the Rings: The Two Towers', '2002', 'Adventure / Fantasy', '8.4', NULL, true, '3 copies in library'),
  ('Lost in Space', '1998', 'Science Fiction / Adventure', '5.4', NULL, true, NULL),
  ('Love Actually', '2003', 'Comedy / Romance', '7.1', NULL, true, NULL),
  ('Love the Beast', '2009', 'Documentary', '6.5', NULL, true, NULL),
  ('Made in Dagenham', '2010', 'Comedy / Drama', '6.7', NULL, true, NULL),
  ('Manchester by the Sea', '2016', 'Drama', '7.6', NULL, true, NULL),
  ('The Matrix', '1999', 'Action / Science Fiction', '8.2', NULL, true, NULL),
  ('Meet Joe Black', '1998', 'Fantasy / Drama', '7.4', NULL, true, NULL),
  ('Meet the Parents', '2000', 'Comedy / Romance', '6.7', NULL, true, NULL),
  ('Mercury Rising', '1998', 'Action / Crime', '6.3', NULL, true, NULL),
  ('Merlin''s Shop of Mystical Wonders', '1996', 'Horror / Fantasy', '2.6', NULL, true, NULL),
  ('Mighty Joe Young', '1998', 'Adventure / Family', '6.3', NULL, true, NULL),
  ('Mike and Dave Need Wedding Dates', '2016', 'Comedy', '6.0', NULL, true, NULL),
  ('A Million Ways to Die in the West', '2014', 'Comedy / Western', '6.1', NULL, true, NULL),
  ('Mimic 2', '2001', 'Horror / Science Fiction', '5.3', NULL, true, NULL),
  ('The Money Pit', '1986', 'Comedy / Romance', '6.5', NULL, true, NULL),
  ('Money Train', '1995', 'Action / Comedy', '5.9', NULL, true, NULL),
  ('Moulin Rouge!', '2001', 'Drama / Romance', '7.5', NULL, true, NULL),
  ('Mr. and Mrs. Smith / Entrapment / The Thomas Crown Affair', NULL, 'Action / Thriller', NULL, NULL, true, '3-film pack'),
  ('The Mummy', '1999', 'Adventure / Action', '7.0', NULL, true, '2 copies in library'),
  ('The Mummy Returns', '2001', 'Adventure / Action', '6.4', NULL, true, NULL),
  ('My Big Fat Greek Wedding', '2002', 'Comedy / Drama', '6.5', NULL, true, NULL),
  ('My Big Fat Greek Wedding 2', '2016', 'Comedy / Romance', '6.0', NULL, true, NULL),
  ('My House in Umbria', '2003', 'Drama / Mystery', '6.1', NULL, true, NULL),
  ('Nanny McPhee', '2005', 'Fantasy / Comedy', '6.7', NULL, true, NULL),
  ('National Treasure', '2004', 'Adventure / Action', '6.7', NULL, true, NULL),
  ('The Natural', '1984', 'Drama', '6.9', NULL, true, NULL),
  ('Natural Born Killers', '1994', 'Crime / Thriller', '7.1', NULL, true, NULL),
  ('The New World', '2005', 'Drama / History', '6.5', NULL, true, NULL),
  ('Night at the Museum', '2006', 'Fantasy / Family', '6.6', NULL, true, NULL),
  ('A Night at the Roxbury', '1998', 'Comedy / Romance', '6.5', NULL, true, NULL),
  ('Nothing to Lose', '1997', 'Comedy / Crime', '6.6', NULL, true, NULL),
  ('Ocean''s Eleven', '2001', 'Thriller / Crime', '7.5', NULL, true, NULL),
  ('Ocean''s Twelve', '2004', 'Thriller / Crime', '6.6', NULL, true, NULL),
  ('The Odyssey', '1997', 'Drama / Adventure', NULL, NULL, true, NULL),
  ('The Other Woman', '2014', 'Comedy / Romance', '6.4', NULL, true, NULL),
  ('Our Little Girl', '1935', 'Comedy / Drama', NULL, NULL, true, 'Shirley Temple'),
  ('The Patriot — Collector''s Edition', '2000', 'Drama / History', '7.2', NULL, true, NULL),
  ('Pearl Harbor', '2001', 'War / Romance', '6.9', NULL, true, NULL),
  ('Pirates of the Caribbean: At World''s End', '2007', 'Adventure / Fantasy', '7.3', NULL, true, NULL),
  ('Pirates of the Caribbean: Dead Man''s Chest', '2006', 'Adventure / Fantasy', '7.4', NULL, true, NULL),
  ('Pirates of the Caribbean: Dead Men Tell No Tales', '2017', 'Adventure / Action', '6.7', NULL, true, NULL),
  ('Pirates of the Caribbean: The Curse of the Black Pearl', '2003', 'Adventure / Fantasy', '7.8', NULL, true, NULL),
  ('Point Break', '1991', 'Action / Thriller', '7.2', NULL, true, '2 copies in library'),
  ('Poor Little Rich Girl', '1936', 'Drama / Family', NULL, NULL, true, 'Shirley Temple'),
  ('Pretty Woman', '1990', 'Romance / Comedy', '7.5', NULL, true, NULL),
  ('The Princess Diaries', '2001', 'Comedy / Family', '7.0', NULL, true, NULL),
  ('Prometheus', '2012', 'Science Fiction / Mystery', '6.6', NULL, true, NULL),
  ('Pulp Fiction — 10th Anniversary', '1994', 'Thriller / Crime', '8.5', NULL, true, NULL),
  ('The Pursuit of Happyness', '2006', 'Drama', '7.9', NULL, true, NULL),
  ('Quartet', '2012', 'Drama / Comedy', '6.5', NULL, true, NULL),
  ('Rebecca of Sunnybrook Farm', '1938', 'Drama / Family', '6.9', NULL, true, 'Shirley Temple'),
  ('Red Dog', '2011', 'Drama / Comedy', '7.3', NULL, true, NULL),
  ('Red Sun', '1971', 'Western', '6.8', NULL, true, NULL),
  ('Resident Evil: Afterlife', '2010', 'Action / Adventure', '6.1', NULL, true, NULL),
  ('Resident Evil: Apocalypse', '2004', 'Horror / Action', '6.4', NULL, true, NULL),
  ('Resident Evil: Extinction', '2007', 'Horror / Action', '6.3', NULL, true, NULL),
  ('Resident Evil: Retribution', '2012', 'Action / Horror', '5.8', NULL, true, NULL),
  ('Return of the Living Dead Part II', '1988', 'Horror / Comedy', '6.4', NULL, true, NULL),
  ('Return to Oz', '1985', 'Adventure / Family', '6.7', NULL, true, NULL),
  ('Road Trip', '2000', 'Comedy / Adventure', '6.2', NULL, true, NULL),
  ('Rocky', '1976', 'Drama', '7.8', NULL, true, NULL),
  ('Romancing the Stone', '1984', 'Romance / Comedy', '6.8', NULL, true, NULL),
  ('Romeo + Juliet', '1996', 'Drama / Romance', '6.8', NULL, true, NULL),
  ('Runaway Bride', '1999', 'Comedy / Romance', '6.1', NULL, true, '2 copies in library'),
  ('Sahara', '2005', 'Action / Adventure', '5.9', NULL, true, NULL),
  ('Saints and Soldiers', '2003', 'War / Drama', '6.3', NULL, true, NULL),
  ('Salmon Fishing in the Yemen', '2012', 'Drama / Romance', '6.4', NULL, true, NULL),
  ('Shallow Hal', '2001', 'Comedy / Drama', '6.2', NULL, true, '2 copies in library'),
  ('The Shawshank Redemption', '1994', 'Drama / Crime', '8.7', NULL, true, '2 copies in library'),
  ('Shooter', '2007', 'Drama / Action', '7.1', NULL, true, '2 copies in library'),
  ('Shopgirl', '2005', 'Comedy / Drama', '5.8', NULL, true, NULL),
  ('Sideways', '2004', 'Comedy / Drama', '7.1', NULL, true, NULL),
  ('Silver Linings Playbook', '2012', 'Drama / Comedy', '7.2', NULL, true, NULL),
  ('The Sixth Sense', '1999', 'Mystery / Thriller', '8.0', NULL, true, NULL),
  ('Space Cowboys', '2000', 'Action / Adventure', '6.4', NULL, true, NULL),
  ('Spartacus — Special Edition', '1960', 'History / War', '7.5', NULL, true, NULL),
  ('The Specialist', '1994', 'Action / Thriller', '5.9', NULL, true, NULL),
  ('Species III', '2005', 'Science Fiction / Action', '5.2', NULL, true, NULL),
  ('Spider-Man — Collector''s Edition', '2002', 'Action / Science Fiction', '7.3', NULL, true, '2 copies in library'),
  ('St. Vincent', '2014', 'Comedy', '7.1', NULL, true, NULL),
  ('Stage Door', '1937', 'Comedy / Drama', '7.1', NULL, true, NULL),
  ('Star Wars: Attack of the Clones', '2002', 'Adventure / Action', '6.6', NULL, true, NULL),
  ('The Station Agent', '2003', 'Drama / Comedy', '7.3', NULL, true, NULL),
  ('Step Brothers', '2008', 'Comedy', '6.6', NULL, true, '2 copies in library'),
  ('The Sting', '1973', 'Comedy / Crime', '8.0', NULL, true, NULL),
  ('Stuart Little — Deluxe Collector''s Edition', '1999', 'Family / Fantasy', '6.1', NULL, true, NULL),
  ('Sucker Punch', '2011', 'Action / Fantasy', '6.2', NULL, true, NULL),
  ('Supergirl', '1984', 'Action / Adventure', NULL, NULL, true, NULL),
  ('Superman II', '1980', 'Science Fiction / Action', '6.8', NULL, true, NULL),
  ('Susannah of the Mounties', '1939', 'Drama / Western', NULL, NULL, true, 'Shirley Temple'),
  ('Swimming Pool', '2003', 'Crime / Thriller', '6.5', NULL, true, NULL),
  ('Taken', '2008', 'Action / Thriller', '7.4', NULL, true, NULL),
  ('Tarzan', '1999', 'Animation / Family', '7.4', NULL, true, 'Disney animated'),
  ('The Texas Chainsaw Massacre: The Beginning', '2006', 'Horror / Thriller', '6.2', NULL, true, NULL),
  ('The Theory of Everything', '2014', 'Drama / Romance', '7.8', NULL, true, NULL),
  ('There''s Something About Mary', '1998', 'Romance / Comedy', '6.6', NULL, true, NULL),
  ('The Thief', '2010', 'Adventure / Fantasy', '6.2', NULL, true, NULL),
  ('Three Kings', '1999', 'Action / Comedy', '6.6', NULL, true, NULL),
  ('Thunderbolt and Lightfoot', '1974', 'Comedy / Action', '6.8', NULL, true, NULL),
  ('Titanic', '1997', 'Drama / Romance', '7.9', NULL, true, '2 copies in library'),
  ('Top Gun: Maverick', '2022', 'Action / Drama', '8.2', NULL, true, NULL),
  ('Trumbo', '2015', 'Drama', '7.2', NULL, true, NULL),
  ('Twilight', '2008', 'Fantasy / Drama', '6.3', NULL, true, NULL),
  ('Twilight Saga: Breaking Dawn Part 1', '2011', 'Adventure / Fantasy', '6.2', NULL, true, NULL),
  ('Twilight Saga: Eclipse', '2010', 'Adventure / Fantasy', '6.2', NULL, true, NULL),
  ('Twilight Saga: New Moon', '2009', 'Adventure / Fantasy', '6.0', NULL, true, NULL),
  ('Under the Tuscan Sun', '2003', 'Romance / Comedy', '6.9', NULL, true, NULL),
  ('Up', '2009', 'Comedy / Animation', '7.9', NULL, true, 'Disney Pixar'),
  ('Van Helsing', '2004', 'Horror / Adventure', '6.4', NULL, true, NULL),
  ('Vanity Fair', '2004', 'Drama / Romance', '5.8', NULL, true, NULL),
  ('Von Ryan''s Express', '1965', 'War / Action', '7.1', NULL, true, NULL),
  ('Wah-Wah', '2005', 'Drama', '5.9', NULL, true, NULL),
  ('The Warriors — Ultimate Director''s Cut', '1979', 'Action / Thriller', '7.7', NULL, true, '2 copies in library'),
  ('Water for Elephants', '2011', 'Drama / Romance', '6.9', NULL, true, NULL),
  ('We Were Soldiers', '2002', 'Action / History', '7.1', NULL, true, '3 copies in library'),
  ('Wedding Crashers', '2005', 'Comedy / Romance', '6.5', NULL, true, NULL),
  ('Welcome to the Sticks', '2008', 'Comedy / Drama', '6.7', NULL, true, 'French comedy'),
  ('What Dreams May Come', '1998', 'Drama / Fantasy', '7.2', NULL, true, NULL),
  ('The Whole Nine Yards', '2000', 'Comedy / Crime', '6.5', NULL, true, NULL),
  ('Wild Target', '2010', 'Action / Comedy', '6.4', NULL, true, NULL),
  ('The Wolf of Wall Street', '2013', 'Crime / Drama', '8.0', NULL, true, NULL),
  ('World War Z', '2013', 'Action / Horror', '6.8', NULL, true, NULL),
  ('X-Men Origins: Wolverine', '2009', 'Adventure / Action', '6.3', NULL, true, NULL),
  ('X-Men', '2000', 'Science Fiction / Fantasy', '7.4', NULL, true, NULL),
  ('You''ve Got Mail', '1998', 'Comedy / Romance', '6.7', NULL, true, NULL),
  ('Are You Being Served? (Series 6)', NULL, 'TV Series, Comedy', NULL, 'tt0068040', true, 'BBC British sitcom'),
  ('As Time Goes By (Series 9)', NULL, 'TV Series, Comedy', NULL, 'tt0105943', true, NULL),
  ('As Time Goes By — Reunion Special', NULL, 'TV Series, Comedy', NULL, 'tt0105943', true, NULL),
  ('Blackadder''s Christmas Carol', NULL, 'TV Series, Comedy', NULL, 'tt0084988', true, 'TV special'),
  ('Boston Legal (Season 4)', NULL, 'TV Series, Comedy / Drama', NULL, 'tt0402711', true, NULL),
  ('Call the Midwife (Series 2)', NULL, 'TV Series, Drama', NULL, 'tt1983079', true, NULL),
  ('Champions (Complete Series)', NULL, 'TV Series, Sci-Fi / Action', NULL, 'tt0062551', true, 'Special Edition'),
  ('Cracker (Series 2)', NULL, 'TV Series, Crime / Drama', NULL, 'tt0105977', true, NULL),
  ('Cracker (Series 3)', NULL, 'TV Series, Crime / Drama', NULL, 'tt0105977', true, NULL),
  ('Downton Abbey (Season 3)', NULL, 'TV Series, Drama', NULL, 'tt1606375', true, NULL),
  ('Fawlty Towers — Complete Collection', NULL, 'TV Series, Comedy', NULL, 'tt0072500', true, 'Remastered'),
  ('Friends (Season 1)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 2)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 3)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 4)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 5)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 6)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 7)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 9)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Friends (Season 10)', NULL, 'TV Series, Comedy', NULL, 'tt0108778', true, NULL),
  ('Game of Thrones (Season 1)', NULL, 'TV Series, Fantasy / Drama', NULL, 'tt0944947', true, 'HBO'),
  ('Game of Thrones (Season 2)', NULL, 'TV Series, Fantasy / Drama', NULL, 'tt0944947', true, 'HBO'),
  ('Game of Thrones (Season 3)', NULL, 'TV Series, Fantasy / Drama', NULL, 'tt0944947', true, 'HBO'),
  ('Game of Thrones (Season 4)', NULL, 'TV Series, Fantasy / Drama', NULL, 'tt0944947', true, 'HBO'),
  ('Game of Thrones (Season 5)', NULL, 'TV Series, Fantasy / Drama', NULL, 'tt0944947', true, 'HBO'),
  ('Gossip Girl (Season 2)', NULL, 'TV Series, Drama', NULL, 'tt0397442', true, NULL),
  ('Hamish & Andy''s Gap Year Asia (Complete)', NULL, 'TV Series, Comedy / Documentary', NULL, 'tt1987154', true, NULL),
  ('Hey Hey It''s Saturday — By Request 2', NULL, 'TV Series, Comedy / Entertainment', NULL, 'tt0174397', true, NULL),
  ('House of Cards', NULL, 'TV Series, Drama', NULL, 'tt1856010', true, NULL),
  ('I Dream of Jeannie (Season 1)', NULL, 'TV Series, Comedy / Fantasy', NULL, 'tt0058815', true, NULL),
  ('I Dream of Jeannie (Season 2)', NULL, 'TV Series, Comedy / Fantasy', NULL, 'tt0058815', true, NULL),
  ('I Dream of Jeannie (Season 3)', NULL, 'TV Series, Comedy / Fantasy', NULL, 'tt0058815', true, NULL),
  ('Love Child (Season 1)', NULL, 'TV Series, Drama', NULL, 'tt2832756', true, NULL),
  ('Modern Family (Season 6)', NULL, 'TV Series, Comedy', NULL, 'tt1442437', true, NULL),
  ('Modern Family (Season 7)', NULL, 'TV Series, Comedy', NULL, 'tt1442437', true, NULL),
  ('Modern Family (Season 8)', NULL, 'TV Series, Comedy', NULL, 'tt1442437', true, NULL),
  ('My Family (Series 6)', NULL, 'TV Series, Comedy', NULL, 'tt0257315', true, NULL),
  ('New Girl (Season 1)', NULL, 'TV Series, Comedy', NULL, 'tt1826940', true, NULL),
  ('New Girl (Season 2)', NULL, 'TV Series, Comedy', NULL, 'tt1826940', true, NULL),
  ('On the Buses (Seasons 1 & 2)', NULL, 'TV Series, Comedy', NULL, 'tt0063936', true, NULL),
  ('On the Buses (Season 3)', NULL, 'TV Series, Comedy', NULL, 'tt0063936', true, NULL),
  ('On the Buses (Season 4)', NULL, 'TV Series, Comedy', NULL, 'tt0063936', true, NULL),
  ('On the Buses (Season 5)', NULL, 'TV Series, Comedy', NULL, 'tt0063936', true, NULL),
  ('On the Buses (Season 6)', NULL, 'TV Series, Comedy', NULL, 'tt0063936', true, NULL),
  ('On the Buses (Season 7)', NULL, 'TV Series, Comedy', NULL, 'tt0063936', true, NULL),
  ('QI Series 1–3', NULL, 'TV Series, Comedy / Talk', NULL, 'tt0380136', true, 'Stephen Fry'),
  ('QI Series 9', NULL, 'TV Series, Comedy / Talk', NULL, 'tt0380136', true, 'Stephen Fry'),
  ('Revenge (Season 1)', NULL, 'TV Series, Drama / Mystery', NULL, 'tt1837642', true, NULL),
  ('Rome (Season 1)', NULL, 'TV Series, Action / Drama', NULL, 'tt0384766', true, 'HBO'),
  ('Rome (Season 2)', NULL, 'TV Series, Action / Drama', NULL, 'tt0384766', true, 'HBO'),
  ('Sons of Anarchy (Season 4)', NULL, 'TV Series, Crime / Drama', NULL, 'tt1124373', true, NULL),
  ('The Big Bang Theory (Season 1)', NULL, 'TV Series, Comedy', NULL, 'tt0898266', true, NULL),
  ('The Big Bang Theory (Season 2)', NULL, 'TV Series, Comedy', NULL, 'tt0898266', true, NULL),
  ('The Big Bang Theory (Season 3)', NULL, 'TV Series, Comedy', NULL, 'tt0898266', true, NULL),
  ('The Big Bang Theory (Season 4)', NULL, 'TV Series, Comedy', NULL, 'tt0898266', true, NULL),
  ('The Big Bang Theory (Season 6)', NULL, 'TV Series, Comedy', NULL, 'tt0898266', true, NULL),
  ('The Vicar of Dibley (Series 1)', NULL, 'TV Series, Comedy', NULL, 'tt0108981', true, 'BBC'),
  ('The Vicar of Dibley (Series 2)', NULL, 'TV Series, Comedy', NULL, 'tt0108981', true, 'BBC'),
  ('The Vicar of Dibley (Series 3)', NULL, 'TV Series, Comedy', NULL, 'tt0108981', true, 'BBC'),
  ('The Vicar of Dibley — The Specials', NULL, 'TV Series, Comedy', NULL, 'tt0108981', true, 'BBC'),
  ('The Vicar of Dibley — A Holy Wholly Happy Ending', NULL, 'TV Series, Comedy', NULL, 'tt0108981', true, 'BBC'),
  ('ABBA — The Definitive Collection', NULL, 'Music, Music / Pop', NULL, NULL, true, NULL),
  ('Guns N'' Roses — Welcome to the Videos', NULL, 'Music, Music / Rock', NULL, NULL, true, NULL),
  ('John Mayer: Any Given Thursday', NULL, 'Music, Music / Concert', NULL, 'tt0362415', true, NULL),
  ('Led Zeppelin', NULL, 'Music, Music / Rock', NULL, NULL, true, NULL),
  ('Neil Diamond — Hot August Night/NYC', NULL, 'Music, Music / Concert', NULL, 'tt1494804', true, NULL),
  ('NRL Magic Moments of the 90s', NULL, 'Music, Sports / Entertainment', NULL, NULL, true, NULL),
  ('Rage Against the Machine — Live at Finsbury Park', NULL, 'Music, Music / Concert', NULL, NULL, true, NULL),
  ('Robin Williams Live on Broadway', NULL, 'Music, Comedy / Concert', NULL, 'tt0330829', true, NULL),
  ('Tahir Live — Premium Collection', NULL, 'Music, Comedy / Concert', NULL, NULL, true, NULL),
  ('ABC Music — Countdown: The Wonder Years 2', NULL, 'Music, Music / Entertainment', NULL, NULL, true, NULL),
  ('Sound Relief', NULL, 'Music, Music / Concert', NULL, NULL, true, NULL),
  ('Black Caviar — The Horse of a Lifetime', NULL, 'Documentary', NULL, 'tt3894358', true, NULL),
  ('Classic Australian Touring Car Races Vol. 1', NULL, 'Sport / Documentary', NULL, NULL, true, NULL),
  ('Dust to Glory', NULL, 'Documentary', NULL, 'tt0386423', true, NULL),
  ('Live to Ride Vol. 1', NULL, 'Sport / Documentary', NULL, NULL, true, NULL),
  ('Manufacturing Dissent', NULL, 'Documentary', NULL, 'tt0961117', true, NULL),
  ('Ride to Live / Live to Ride Vol. 2', NULL, 'Sport / Documentary', NULL, NULL, true, NULL),
  ('Sicko', NULL, 'Documentary', NULL, 'tt0386032', true, NULL),
  ('The Royal Air Force at War', NULL, 'Documentary / History', NULL, 'tt11871076', true, NULL);